name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
    
    - name: Run Cimon
      uses: cycodelabs/cimon-action@v0
      with:
        client-id: ${{ secrets.CIMON_CLIENT_ID }}
        secret: ${{ secrets.CIMON_SECRET }}
